branch-defaults:
  master:
    environment: crunchy-dev
    group_suffix: null
environment-defaults:
  django-env:
    branch: null
    repository: null
global:
  application_name: crunchy
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  repository: origin
  sc: git
