branch-defaults:
  master:
    environment: django-env
    group_suffix: null
environment-defaults:
  django-env:
    branch: master
    repository: origin
global:
  application_name: crunchy
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: python3.4
  default_region: us-west-2
  profile: eb-cli
  repository: origin
  sc: git
